feat: storage main page UI 구현
picktoss/pick-toss-next pull request #10
Opened 2024-04-30 18:04 UTC by woo-jk

## 개요
- 공부창고 메인 페이지 UI 구현

### 세부 내용
<img width="1340" alt="스크린샷 2024-05-01 오전 3 02 07" src="https://github.com/picktoss/pick-toss-next/assets/73513965/dd801569-7e33-4527-a873-91f25ec62e70">
- 공부창고 메인 페이지 UI 구현
- 각 페이지 layout을 (routes)의 layout으로 통합

### 관련 링크

2024-04-30 18:20 UTC, jw-r requested changes
LGTM!!

코맨트만 확인 부탁드려요~

2024-04-30 18:20 UTC, jw-r commented on src/app/(routes)/layout.tsx
> +      </div>
너무 좋네요!
다만 이렇게 작성되면 children 컴포넌트에서 `h-full`을 적용했을 때 스크롤이 생기는 문제가 발생할 것 같습니다.

예를 들어 다음과 같이 적용해보면 좋겠네요!
```suggestion
      <div className="mx-auto max-w-[1440px] w-full px-20">
        <HeaderLayout />
        <div className="pt-8">
          {children}
        </div>
      </div>
```

2024-04-30 18:34 UTC, jw-r approved these changes

2024-04-30 18:35 UTC, merged

2024-05-01 00:28 UTC, woo-jk commented on src/app/(routes)/layout.tsx
> +      </div>
아 그러네요. 저 패딩 값은 레이아웃이 아닌 페이지 컴포넌트(혹은 하위 레이아웃 컴포넌트)에서 알아서 처리해주는게 더 적절해보입니다!