refactor: main page
picktoss/pick-toss-next pull request #203
Opened 2024-09-11 06:13 UTC by rabyeoljji

## 개요

### 세부 내용
- #### 성능 최적화를 위해
- prefetch 적용
- isLoading -> isPending으로 변경 (React v5 반영)

<br/>

- #### 코드 가독성 개선을 위해
- MakeQuizDrawerDialog 컴포넌트 drawer 부분과 dialog 부분 분리
- MakeQuizDialog 내부 selector 부분 분리 (category/documents/quizCount)
- MakeQuizDrawer 컴포넌트 내부 컴포넌트 분리 (FolderDrawer/DocumentDrawer)
- QuizBanner에서 이미지를 렌더링하던 부분 컴포넌트로 분리
- QuizBanner 내부 컴포넌트들 별도 파일로 분리
- 추후 유지보수가 용이하도록 몇 가지 주석 추가

<br/>

- #### 코드 중복을 최소화하기 위해
- selector 분리 시 발생하는 ignoreId 부분 계산값을 useMemo로 저장
- drawer/dialog 공통으로 사용되는 filteredIgnoreIds 상위 컴포넌트로 빼고 props로 전달
- FolderDrawer/DocumentDrawer 공통으로 사용되는 SelectDrawerContent의 경우 별도 컴포넌트로 분리

<br/>

- #### 코드 컨벤션 유지를 위해
- types 디렉토리 하위 quiz.ts 생성 (MakeQuizDrawerDialog 컴포넌트에 있던 타입 정의)

<br/>

- #### 불필요한 리렌더링을 방지하기 위해
- MakeQuizDialog 내부 selector 컴포넌트들을 React.memo로 memoization해주었습니다.
- handleCreateQuizzes를 useCallback으로 감싸주었습니다.

<br/>

- #### 디버깅
- 리팩토링 과정에서 퀴즈를 생성하려고 할 때, category에 맞는 document list가 렌더링 되지 않는 현상 발생
- 원인 : 컴포넌트 분리 과정에서 useCheckList 훅에 초기 빈 배열 []을 넘겨주고 set을 이용해 만든 documentList를 이용하고 있던 코드를 set 없이 그대로 사용하게 되어 발생
- documentList를 상위 컴포넌트로부터 props로 받아 useCheckList에 넘겨주었습니다.

### 관련 링크

2024-09-12 13:45 UTC, jw-r requested changes
근아님 너무 고생하셨습니다!
렌더링 최적화까지 고려해주시다니 너무 좋습니다👍

현재 `quiz-maker-dialog`, `quiz-maker-drawer`가 제대로 동작하지 않고 있는 것 같아요!
document가 선택이되지 않거나, 선택이 되는 것 처럼만 보이는 상태입니다
사용자가 선택한 documentIds가 어디에 필요한 데이터인지 한번 점검해봐도 좋을 것 같아요🙌

2024-09-12 13:45 UTC, jw-r commented on src/views/main/components/make-quiz-drawer-dialog.tsx
> +        </Div100vh>
MakeQuizDrawer가 마치 drawer 컴포넌트를 연상시키는 것 같습니다!
위 부분을 `MakeQuizDrawerContent`로 분리해도 좋을 것 같아요!

2024-09-12 13:45 UTC, jw-r commented on src/views/main/components/make-quiz-drawer-dialog.tsx
> +          )}
이 부분도 MakeQuizDialogContent로 분리해도 좋을 것 같아요!

2024-09-13 02:31 UTC, rabyeoljji commented
> 근아님 너무 고생하셨습니다! 렌더링 최적화까지 고려해주시다니 너무 좋습니다👍
> 
> 현재 `quiz-maker-dialog`, `quiz-maker-drawer`가 제대로 동작하지 않고 있는 것 같아요! document가 선택이되지 않거나, 선택이 되는 것 처럼만 보이는 상태입니다 사용자가 선택한 documentIds가 어디에 필요한 데이터인지 한번 점검해봐도 좋을 것 같아요🙌

아 그렇군요ㅠㅠ 다시 확인해보고 디버깅해서 올리겠습니다!

2024-09-17 08:34 UTC, jw-r approved these changes
너무 잘 수정해주셨네요👍👍👍
몇가지 코맨트만 확인 부탁드려요~!

2024-09-17 08:34 UTC, jw-r commented on src/views/main/components/make-quiz-dialog-selectors.tsx
selector들을 잘 분리해주셨네요👍
파일 이름에 dialog가 포함될 필요가 있을지는 조금 의문이 드는 것 같아요!
완전히 별개로 재사용될 수도 있을 것 같아서요!

2024-09-17 08:34 UTC, jw-r commented on src/views/main/components/make-quiz-dialog.tsx
파일 이름이 ~-dialog | ~~drawer라면
<Dialog /> <Drawer /> 컴포넌트를 사용하는 컴포넌트라는 느낌이 강하게 드는 것 같아요!
실제로 다른 곳에서 그런 방식으로 사용되고 있기도 하구요🙌
make-quiz-dialog-content하고 이름 짓는 건 어떨까요?

```tsx
<DrawerContent>
  <MakeQuizDrawerContent />
</DrawerContent>
```
컨텐츠는 컨텐츠인데 Drawer Dialog의 컨텐츠다라는 느낌이 자연스럽게 느껴지는 것 같아서요!

근아님의 의견도 궁금하네요👍

2024-09-17 08:34 UTC, jw-r commented on src/views/main/components/quiz-banner.tsx
> +  const [remainingTime, setRemainingTime] = useState(calculateTimeUntilTomorrowMidnight())
이 방식은 리렌더링 될 때마다 calculateTimeUntilTomorrowMidnight() 함수가 실행됩니다!
결과값은 무시되지만요
`() => calculateTimeUntilTomorrowMidnight()` 와 같이 콜백함수 형태로 넣어줘야 할 것 같아요👍

2024-09-17 08:34 UTC, jw-r commented on src/views/main/components/make-quiz-dialog-selectors.tsx
> +  }, [newDocumentList])
지금 적용시키지 않아도 괜찮습니다!
Context로 활용하면 하나의 useCheckList 상태로 문서 선택 여부를 관리할 수 있겠네요!

2024-09-17 13:32 UTC, rabyeoljji commented on src/views/main/components/quiz-banner.tsx
> +  const [remainingTime, setRemainingTime] = useState(calculateTimeUntilTomorrowMidnight())
아 그렇군요! 또 하나 배워갑니다ㅎㅎ👍

2024-09-17 13:38 UTC, rabyeoljji commented on src/views/main/components/make-quiz-dialog.tsx
아아 이게 dialog는 그렇게 네이밍했을 때 괜찮은데 drawer는 make-quiz-dialog-contents 파일에서 내부 컴포넌트들을 정의해서 사용하다보니까 drawer랑 뭔가 컨벤션을 맞추고 싶어서 그대로 두었는데 정우님 말씀대로 저렇게 네이밍하는게 더 명확한 표현인 것 같아요! 이렇게 수정하고 drawer쪽 내부 컴포넌트들을 사용하는 파일 이름을 수정하면 어떨까 싶습니다ㅎㅎ

2024-09-18 02:19 UTC, rabyeoljji commented on src/views/main/components/make-quiz-dialog-selectors.tsx
> +  }, [newDocumentList])
맞네요! 이 부분이 저도 더 개선할 수 있을 것 같았는데! context를 활용할 생각을 못했네요😂 혹시 디렉토리 구조 context도 분리해서 따로 관리하는 쪽으로 하는게 좋을까요, 아니면 컴포넌트랑 같이 두는 쪽으로 하는게 좋을까요?

2024-09-22 04:51 UTC, jw-r approved these changes
너무 고생하셨습니다!
컴포넌트들이 잘 나누어져서 가독성이 좋았어요👍👍👍

몇가지 코맨트만 확인 부탁드려요🙌

2024-09-22 04:51 UTC, jw-r commented on src/types/quiz.ts
> +}
```suggestion
```

2024-09-22 04:51 UTC, jw-r commented on src/views/main/components/make-quiz-drawer-steps.tsx
> +  doc: ReturnUseCheckList<SelectDocumentItem>
따로 타입을 작성해주는 것도 좋지만 아래와 같이 타입스크립트에서 제공하는 타입을 활용하는 것도 좋을 것 같아요!

```suggestion
  folder: ReturnType<typeof useCheckList<SelectCategoryItem>>
  doc: ReturnType<typeof useCheckList<SelectDocumentItem>>
```

2024-09-22 04:51 UTC, jw-r commented on src/views/main/components/make-quiz-drawer-content.tsx
> +  })
이 folder와 doc을 컨텍스트로 관리하면 데스크탑 모바일 상관없이 사용할 수 있을 것 같아요!
ignoreIds는 Provider 단에서 제공하니, 실제 사용처에서는 상호작용이 가능한 체크 리스트만 관리하면 되니 역할 분담이 더욱 잘 될 것 같다는 생각도 들었습니다!

2024-09-23 01:10 UTC, rabyeoljji commented on src/views/main/components/make-quiz-drawer-content.tsx
> +  })
좋은 생각입니다👍 다음에 추가적으로 리팩토링하면 적용해볼게요!

2024-09-25 08:38 UTC, merged