Refactor profile
picktoss/pick-toss-next pull request #204
Opened 2024-09-20 12:32 UTC by rabyeoljji

## 개요

### 세부 내용
- #### refactor
- 디렉토리 구조 수정
- 각 section 별로 content 컴포넌트로 분리
- 컴포넌트 분리에 따른 구조 수정
- 몇 가지 주석 추가
- 로딩 처리를 위해 suspense 코드 추가

<br/>

- #### fix
- notification 에러 디버깅: useSession() => auth()로 수정

### 관련 링크

2024-09-22 11:56 UTC, jw-r requested changes
이번에도 컴포넌트를 너무 잘 분리해주신 것 같아요👍👍👍👍👍
저희가 app 폴더 하위에서 혹은 view 폴더 하위에서 각각 컴포넌트의 추상화 레벨을 어느정도로 가져갈지 이야기 나눠보는 것도 재미있겠네요!!

2024-09-22 11:56 UTC, jw-r commented on src/shared/hooks/use-user.ts
> +  const session = await auth()
어떤 문제가 있어서 auth 로 바꿔주셨을까요?
useUser는 custom hook으로 client component 에서만 사용이 가능합니다!
auth는 서버 side의 session 호출 방식으로 알고있어서요🙌

2024-09-22 11:56 UTC, jw-r commented on src/views/notification-email/index.tsx
> +  const { user } = await useUser()
client 컴포넌트에 async를 붙일 수 있나요?
이 부분이 잘 동작하는지 궁금해요🤩

2024-09-22 11:56 UTC, jw-r commented on src/views/notification/index.tsx
> +  const { user } = await useUser()
server components라면 다른 방식으로 user를 가져와야할 것 같아요!
useUser는 리액트의 hook 규칙을 따르고 있는 custom hook이기 때문에 client 컴포넌트에서 사용되어야 할 것 같습니다🙌

2024-09-23 01:25 UTC, rabyeoljji commented
> 이번에도 컴포넌트를 너무 잘 분리해주신 것 같아요👍👍👍👍👍 저희가 app 폴더 하위에서 혹은 view 폴더 하위에서 각각 컴포넌트의 추상화 레벨을 어느정도로 가져갈지 이야기 나눠보는 것도 재미있겠네요!!

저도 추상화 레벨을 어느정도로 해야할지가 좀 어렵더라고요😂 저는 우선 방법론 중에 Atomic Design에 기반한 추상화를 하면서도 템플릿이랑 페이지의 경우 너무 과도하게 추상화하지 않으려고 하는 편이긴 하는데 정우님 생각은 어떠신가요?

2024-09-23 01:35 UTC, rabyeoljji commented on src/views/notification/index.tsx
> +  const { user } = await useUser()
> server components라면 다른 방식으로 user를 가져와야할 것 같아요! useUser는 리액트의 hook 규칙을 따르고 있는 custom hook이기 때문에 client 컴포넌트에서 사용되어야 할 것 같습니다🙌

맞습니다😂 발생한 문제가 이것 때문이었어요...ㅎㅎ 'use client'를 깜박했습니다... 작동을 안하길래 우선 임시로 auth로 저렇게 두고 계속 문제 파악 중이었는데 PR 업데이트 하겠습니다ㅎㅎ

2024-10-04 01:13 UTC, merged