feat: quiz note
picktoss/pick-toss-next pull request #213
Opened 2024-10-08 08:12 UTC by rabyeoljji

## 개요
<img src="https://github.com/user-attachments/assets/e4ad580d-18e6-48bc-8d76-89c6e8416a28" width="15%"/>
<img src="https://github.com/user-attachments/assets/274f3bc9-c0b3-4e93-bee9-184d62455a5e" width="15%"/>
<img src="https://github.com/user-attachments/assets/3d777406-3556-4676-b28b-7b5f37381fdc" width="15%"/>
<img src="https://github.com/user-attachments/assets/8bc254e2-1982-49c3-8da2-0c4035d1842e" width="15%"/>
<img src="https://github.com/user-attachments/assets/6542576a-10f8-43b9-abbb-ddf543af0223" width="15%"/>
<img src="https://github.com/user-attachments/assets/87eae832-e485-4f15-90e9-fe485fd5d08b" width="15%"/>

### 세부 내용
- 퀴즈 노트 페이지 퍼블리싱

+ 하는 김에 인터렉션 부분 중에 현재 구현할 수 있는 부분들까지 구현했습니다
swipe 부분은 우선 framer motion으로 구현했는데 더 좋은 방법이 있다면 변경 시도해볼 예정

### 관련 링크

2024-10-10 13:22 UTC, jw-r requested changes
와우... 많은 작업량인데 정말 고생하셨습니다
몇가지 코맨트 확인 부탁드려요!

2024-10-10 13:22 UTC, jw-r commented on src/views/v3/quiz-note/components/animate-buttons.tsx
> +              )
옛날 리액트가 생각나네요 ㅋㅋ
너무 좋습니다👍

2024-10-11 02:13 UTC, rabyeoljji commented on src/shared/components/ui/checkbox.tsx
> +const CheckBoxIcon = () => {
엇 그러네요ㅋㅋㅋㅋ 크게 의미가 없어서 수정하려고 합니다!

2024-10-11 02:28 UTC, rabyeoljji commented on src/shared/components/v3/icon/svg-components.tsx
> +  const [imageId, setImageId] = useState<string>('')
> 클라이언트에서만 UUID를 생성하는 특별한 이유가 있나요??

아 이게 페이지가 처음 서버에서 렌더링 될 때는 서버에서 생성된 uuid가 사용되고 이후 클라이언트에서 재렌더링되면 클라이언트에서 uuid가 생성돼서 값이 일치가 안되는 현상이 발생하더라고요! 클라이언트에서만 uuid를 생성해서 사용하면 일관된 고유값을 보장할 수 있어서 이렇게 작성했습니다🙂

2024-10-11 02:30 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/svg-icons.tsx
네 일단은 이 페이지에서만 사용될 것 같아서 스코프를 제한했는데 추후 다른 곳에서도 사용되는 경우 공통 아이콘으로 넣을까 생각했어요!

2024-10-11 02:31 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/header.tsx
> +        className={cn(
아 그런가요? 그럼 전체 수정하도록 할게요~

2024-10-11 02:36 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/folder-select-drawer.tsx
> +      <MaterialDrawer
> material ui를 사용한 Drawer도 정말 편리해보이네요!👍 다만 shadcn을 사용하고 있는 저희 환경에서 meterial을 함께 사용해야할 이유가 있었을까요?

아 shadcn을 이용해서 drawer을 위에서 내려오도록 하는 방법을 찾지 못해서 material을 넣어봤는데 shadcn에서 drawer 방향을 조정할 수 있을까요?

2024-10-11 02:49 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/quiz-note-dialog.tsx
> +          {dialogState.type === 'delete' && '폴더 삭제'}
> folder drawer가 열려있는 상태에서 header의 우측 아이콘을 눌렀을 때, folder drawer각 닫히는 건 근아님께서 의도하신 걸까요?

네 맞습니다! header 우측 아이콘이 담당하는 기능 모두 drawer가 없는 화면에서의 인터렉션을 필요로 한다고 생각했어요

> dialogState를 전역에서 추적하는 이유가 Dialog의 재사용성을 극대화하기 위함이군요! 너무 좋습니다🤩
> 
> 조금 과한 추상화가 될 수는 있을 것 같아요! 저희는 이미 잘 만들어진 Dialog 컴포넌트를 가지고 있으니까요👍 각각의 Dialog를 분리하고 한 Trigger에 해당 Dialog를 매핑해보는 방식을 고려해봐도 좋을 것 같습니다!

저도 이 부분에 대해 고민을 해보다가 create와 edit이 거의 동일한 구조를 가지고 있어 한 번 더 추상화를 할 수 있을 것 같더라고요! 그래서 저런 방식을 시도해봤습니다ㅎㅎ

2024-10-11 02:53 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/swipeable-note-card.tsx
> +    }
> 이 로직은 사용자가 스와이프 영역을 터치하고 있는 상태에서는 버벅거림을 발생시킬 가능성이 있을 것 같습니다! useMotionValue에 대해서 한번 리서치해보시는 것도 좋을 것 같아요! useAnimation과 함께 현재 구현해주신 기능을 보다 안정적으로 구현할 수 있을 것 같아요!

오 그렇지 않아도 저도 버벅거림 없이 좀 더 안정적으로 구현할 수 있으면 좋겠다 생각했는데 감사합니다😲 찾아보고 개선해볼게요ㅎㅎ

2024-10-11 02:56 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/animate-buttons.tsx
> +              )
어떻게 하면 코드 중복을 최소화할 수 있을까 하다가 도달한 지점입니다ㅋㅋ큐ㅠㅠ😂

2024-10-11 02:59 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/dimmed-background.tsx
> +const DimmedBackground = ({ isExpanded }: { isExpanded: boolean }) => {
> 이 컴포넌트에 DimmedBackground는 포함되는 컴포넌트라는 생각이 들었습니다! `DissolveMenu (예시..)`와 같은 네이밍을 짓고 그 안에 DimmedBackground와 메뉴들을 포함시켜보면 어떨까요?

오 조금 이해가 명확하게 안되는데 혹시 DimmedBackground와 AnimateButtons를 포함하는 공통 컴포넌트를 말씀하신게 맞을까요?

2024-10-11 08:30 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/folder-select-drawer.tsx
> +      <MaterialDrawer
오 방법 찾았습니다! shadcn drawer 컴포넌트를 사용하는 방법으로 코드 수정해서 커밋했습니다! 몇가지 사용처에서 컨트롤하면 좋을 것 같아서 기존 Drawer 컴포넌트를 살짝 변경했어요!

2024-10-11 11:33 UTC, jw-r commented on src/shared/components/v3/icon/svg-components.tsx
> +  const [imageId, setImageId] = useState<string>('')
호옹.. 이상한 현상이군요!
제가 만든 `generateUUID` 함수 말고 리액트의 `useId`를 사용해서 해결할 수 있을 것 같습니다!
[React 공식문서 useId](https://ko.react.dev/reference/react/useId)

서버 컴포넌트에서도 동작하기 때문에, svg가 클라이언트 사이드에서 리렌더링 되는 문제(현재 코드에서 발생할 수 있는 문제)를 방지할 수 있을 것 같아요!

2024-10-11 11:40 UTC, jw-r commented on src/views/v3/quiz-note/components/dimmed-background.tsx
> +const DimmedBackground = ({ isExpanded }: { isExpanded: boolean }) => {
아하 현재 text.content와 animate buttons 들이 분리되어 있군요!
`DimmedBackground`는 말그대로 dimmed 된 배경만을 뜻하는 것 같아서요!
페이지 연동하기 등의 text.content는 각 버튼들을 기준으로 absolute로 존재해도 되겠다고 생각했습니다👍

2024-10-11 11:43 UTC, jw-r commented on src/views/v3/quiz-note/components/dimmed-background.tsx
> +const DimmedBackground = ({ isExpanded }: { isExpanded: boolean }) => {
```tsx
const DissolveMenu = ({ open }) => {
  return (
    <DimmedBackground>
      <p>노션 페이지를 수정해도 업데이트 할 수 있어요</p>
      {/* 버튼들 */}
    </DimmedBackground>
  )
}
```

구조로 보면 위와 같을 것 같습니다!

2024-10-11 11:45 UTC, jw-r commented on src/views/v3/quiz-note/components/folder-select-drawer.tsx
> +      <MaterialDrawer
오오 멋집니다!
<img width="477" alt="image" src="https://github.com/user-attachments/assets/92898784-0b49-4cf3-a73b-378ff07f03b8">
 폴더 만들기 모달이 떠있을 때, 왜 header 영역은 dimmed 처리되지 않는걸까요?

2024-10-11 11:48 UTC, jw-r commented on src/views/v3/quiz-note/components/folder-select-drawer.tsx
> +      <MaterialDrawer
이 부분은 header 의 "전체 노트" 를 trigger로 취급하는 Dropdown 컴포넌트로 볼 수도 있겠네요!
물론 근아님이 작업해주신 것도 너무 좋습니다👍

2024-10-11 11:57 UTC, jw-r commented on src/views/v3/quiz-note/components/quiz-note-dialog.tsx
> +          {dialogState.type === 'delete' && '폴더 삭제'}
적용해주신 방법으로 인해 코드 중복이 크게 줄어든 것 같네요!

다만, 상태 관리를 따로 해줘야하는 점이 코드의 응집도를 낮출 수 있겠다는 생각이 드는 것 같습니다!
만약 거의 동일한 구조를 가지고 있다면 아래와 같이 추상화해보는 건 어떨까요?
```tsx
const DeleteDialog = () => {
  return <QuizNoteDialog open={...} onOpenChange={...} title="폴더 만들기" onConfirm={() => {}} content={<div></div>} />
}
```

한번 더 추상화를 해서 코드의 중복은 줄였지만, QuizNoteDialog가 현재 어떤 모달이 열린건지 등에 대해 신경쓰지 않아도 될 것 같아요!

2024-10-11 12:00 UTC, jw-r commented on src/views/v3/quiz-note/components/swipeable-note-card.tsx
> +    }
와우.... 기가 맥히게 수정하셨네요!
동작이 너무 부드럽습니다🤩

2024-10-11 13:03 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/quiz-note-dialog.tsx
> +          {dialogState.type === 'delete' && '폴더 삭제'}
와우👍 정말 깔끔한 방법인 것 같아요! 확실히 제가 이 방식으로 컴포넌트를 추상화하는 데 익숙하지 않아서 이렇게 추상화할 생각을 못했네요...! 이런 방식으로 수정해보겠습니다ㅎㅎ

2024-10-12 07:32 UTC, jw-r approved these changes
정말 귀한 PR이네요 ㄷㄷ...
너무너무 고생하셨습니다🤩

몇가지 코맨트만 확인 부탁드려요👍

2024-10-12 07:32 UTC, jw-r commented on src/views/v3/quiz-note/components/add-note-menu.tsx
와우 너무 깔끔하네요👍

2024-10-12 07:32 UTC, jw-r commented on src/views/v3/quiz-note/components/swipeable-note-card.tsx
동작 너무 깔끔해요!

2024-10-12 07:32 UTC, jw-r commented on src/views/v3/quiz-note/components/quiz-note-dialog.tsx
만드시면서 느끼셨을 수 있는데, open, onOpenChange등 prop drilling이 조금 번거롭게 느껴지네요!
또, 아직까지도 Dialog 내부에 "삭제하기"에 대한 조건문이 존재하구요

중복을 줄이는 것도 중요하지만, 앞으로도 위와 같은 상황을 고려하면서 어떤 구조가 보다 유지보수에 용이할까 고민해보시면 너무 좋을 것 같아요!

이번엔 너무너무 고생하셨습니다👍

2024-10-14 05:45 UTC, rabyeoljji commented on src/views/v3/quiz-note/components/quiz-note-dialog.tsx
> 만드시면서 느끼셨을 수 있는데, open, onOpenChange등 prop drilling이 조금 번거롭게 느껴지네요! 또, 아직까지도 Dialog 내부에 "삭제하기"에 대한 조건문이 존재하구요
> 
> 중복을 줄이는 것도 중요하지만, 앞으로도 위와 같은 상황을 고려하면서 어떤 구조가 보다 유지보수에 용이할까 고민해보시면 너무 좋을 것 같아요!
> 
> 이번엔 너무너무 고생하셨습니다👍

맞아요...! 사실 코드 중복을 줄이는 것과 유지보수에 용이하게 하는 그 적절한 지점을 찾는게 좀 어렵더라고요ㅠㅠ 아직 모르는 방법이 많아서 더 그런 것 같아서 계속 배워나가는 중입니다ㅎㅎ

2024-10-14 05:46 UTC, merged