feat: quiz note - depth1
picktoss/pick-toss-next pull request #216
Opened 2024-10-17 04:08 UTC by rabyeoljji

## 개요
![스크린샷 2024-10-17 130410](https://github.com/user-attachments/assets/15864481-00f0-4a5f-adb9-58cbacb3b0e6)

### 세부 내용
- 퀴즈 노트 페이지 depth1 퍼블리싱 작업
- 삽입한 스크린샷 이미지에서 빨간 네모 박스 영역을 제외한 나머지 부분 완료했습니다!
- 남은 영역도 작업이 완료되면 업데이트하겠습니다!

### 관련 링크

2024-10-18 13:19 UTC, rabyeoljji commented
@jw-r 
코드리뷰에서 정우님이랑 의견 나눠보고 싶었던 부분이 있습니다ㅎㅎ

- 퀴즈노트쪽 view가 좀 여러개가 나오다보니 여러 폴더에서 사용되는 공통 컴포넌트(퀴즈 생성 drawer 같은)가 생기더라고요... 전체 shared에 넣기에는 좀 애매한 것 같아서 이걸 어떻게 분리하면 좋을까 생각하다가 view/shared를 만들어 넣어뒀는데 저 방법이 최선일지, 혹시 정우님 의견은 어떤지 궁금합니다!

- 노트 수정 관련해서 기존 픽토스 route 구성 방식과는 조금 다르게 note/[noteId]/modify 이렇게 구조를 가져가면 흐름이나 depth와 일치하는 부분이 있는 것 같아서 이렇게 변경해봤는데 정우님 의견은 어떤지 궁금합니다!

2024-10-19 16:30 UTC, jw-r requested changes
너무너무 고생하셨습니다!
몇가지 코맨트 확인 부탁드려요:)

Dialog 등의 응집도와 추가 상태를 선언하는 것들에 대해서 고민해보면 좋을 것 같아요!

2024-10-19 16:30 UTC, jw-r commented on src/views/quiz-note/components/animate-buttons.tsx
> +  }
여기서는 button의 key를 알기 어려울 수 있을 것 같아요.
`addNoteButtons` 내부에 href를 같이 가지고 있으면 어떨까요?

2024-10-19 16:30 UTC, jw-r commented on src/views/quiz-note/components/note-card.tsx
이건 이제 안쓰이는 컴포넌트인걸까요?

2024-10-19 16:30 UTC, jw-r commented on src/views/quiz-note/components/set-folder-name-content.tsx
너무 잘 분리해주셨지만, Dialog의 부품이 따로 떨어져있는 느낌도 드는 것 같아요!
폴더 이름을 set하는 Dialog는 `SetFolderNameDialog` 로 응집되어있으면 어떨까요?
상황에 따라 다르겠지만 개인적으로 응집도를 높이는 것이 중복을 줄이는 것보다 중요하다고 생각해요!

2024-10-19 16:30 UTC, jw-r commented on src/views/shared/new-quiz-drawer.tsx
> +                onClick={() => setIsOpenMoreStar(true)} // 임시
임시로 작성해주셨는데, MoreStarDialog의 open 상태를 상위 컴포넌트에서 관리해주어야했던 이유가 궁금해요!

2024-10-19 16:30 UTC, jw-r commented on src/views/shared/note-type-icon.tsx
> +  iconClassName: string
사소하지만 HTMLElement['className'] 타입을 지정하면, tailwind의 자동완성을 사용할 수 있어요!

2024-10-19 16:30 UTC, jw-r commented on src/views/shared/quiz-note-dialog.tsx
> +const QuizNoteDialog = ({ open, onOpenChange, title, content, onConfirm, confirmText }: Props) => {
마찬가지로 trigger를 해당 컴포넌트에 포함시켜 불필요한 상태를 줄이고 컴포넌트 응집도를 높힐 수 없을까 고민해봐도 좋을 것 같습니다!

2024-10-19 16:30 UTC, jw-r commented on src/views/shared/move-note-drawer.tsx
>    const [isOpen, setIsOpen] = useState(false)
이것도 불필요한 상태로 보여요!

다음과 같은 코드가 있는데, DrawerClose 컴포넌트는 내부적으로 open의 상태를 false로 바꿔주는 로직을 가지고 있기 때문에 중복로직이 수행되고 있습니다!
```tsx
<DrawerClose asChild>
  <button className="text-text-primary" onClick={() => setIsOpen(false)}>
    <Icon name="cancel" className="size-[24px]"></Icon>
  </button>
</DrawerClose>
```

2024-10-19 16:30 UTC, jw-r commented on src/views/shared/more-star-dialog.tsx
> +const MoreStarDialog = ({ isOpen, setIsOpen }: Props) => {
trigger가 외부에 있어야 할 이유가 궁금해요!

2024-10-19 16:30 UTC, jw-r commented on src/views/note-search/components/search-list.tsx
> +    <div className="h-[calc(100dvh-88px-56px)] p-[16px] text-text1-medium overflow-y-auto">
```suggestion
    <div className="h-[calc(100dvh-88px-56px)] overflow-y-auto p-[16px] text-text1-medium">
```

2024-10-19 16:30 UTC, jw-r commented on src/views/note/components/add-collection-drawer.tsx
> +  const [isOpen, setIsOpen] = useState(false)
불필요한 상태 선언인 것 같습니다!

2024-10-19 16:30 UTC, jw-r commented on src/views/note/index.tsx
네이밍을 note-detail 로 하는 건 어떨까요?
어디서 쓰이는 컴포넌트인지 바로 파악하기가 어려웠던 것 같아요!

2024-10-19 16:30 UTC, jw-r commented on src/views/note/index.tsx
추가적으로 현재 아래의 폴더 구조를 가지고 있는데,
![image](https://github.com/user-attachments/assets/51309946-8b29-46cb-b3bd-d8fb97fa3d33)

create-note, modify-note, note-detail, note-search, quiz-note 등이 note 폴더 하위에 들어가도 좋을 것 같아요!

2024-10-19 16:30 UTC, jw-r commented on src/views/quiz-note/components/delete-note-button.tsx
> +      </button>
이건 QuizNoteDialog의 Trigger로 보이는데, 따로 이렇게 작성해주신 이유가 있을까요?

button을 QuizNoteDialog의 Trigger로 포함시키고, 이 컴포넌트 자체가 DeleteNoteDialog가 되어도 될 것 같아요👍

2024-10-19 16:30 UTC, jw-r commented on src/shared/components/ui/button.tsx
> +        special: 'bg-gradient-to-r from-blue-400 from-0% via-[#FFA25F] to-orange-500 to-70%',
이렇게 작성해주면 어떤 점이 바뀌는 걸까요?

2024-10-19 16:30 UTC, jw-r commented on src/views/quiz-note/components/menu-dots-button.tsx
> +  const [isOpenDelete, setIsOpenDelete] = useState(false)
마찬가지로 따로 상태를 두지 않고 동일한 기능을 하도록 작성할 수 있을 것 같아요!

2024-10-21 01:57 UTC, rabyeoljji commented on src/views/modify-note/components/header.tsx
> +}
아 dialog trigger를 이용해서 한 번에 관리할 수가 있었군요!

2024-10-21 02:00 UTC, rabyeoljji commented on src/views/note-search/index.tsx
> +          />
네 맞아요ㅎㅎ 저도 작성하면서 나중에 left도 right처럼 받는 방식으로 수정하는게 좋을까 생각했습니다ㅎㅎ 생각난김에 이번에 다른 부분들이랑 같이 수정해서 머지할까봐요!

2024-10-21 02:13 UTC, rabyeoljji commented on src/views/shared/replay-quiz-drawer.tsx
> +  const [isOpen, setIsOpen] = useState(false)
앗 컴포넌트 분리하면서 삭제를 깜박했어요ㅋㅋ큐ㅠㅠ

2024-10-21 02:22 UTC, rabyeoljji commented on src/views/note/components/header.tsx
> +  ]
아아 그 방법도 있겠군요..! 그럼 공통으로 사용되는 dialog 컴포넌트도 그냥 trigger를 받아서 isOpen 상태관리를 다 없앨 수 있을 것 같은데... 추후에 한꺼번에 적용해서 수정해볼게요!

2024-10-21 02:24 UTC, rabyeoljji commented on src/views/create-note/editor/index.tsx
좋습니다!

2024-10-21 02:28 UTC, rabyeoljji commented on src/views/note/components/header.tsx
> +                  className={cn('ml-[16px]', isMenuOpen && 'text-icon-disabled')}
저도 그걸 dropdown 밖에서 사용해도 되는건가 생각을 잠깐 했는데ㅋㅋ큐ㅠ 음... 우선 순전히 저 css를 위한 상태니까 `data-[state=open]` 을 이용한 방식으로 수정하고 나중에 좀 더 고민해보고 유지보수차원에서 사용을 하지 않는 게 좋을 것 같다고 판단되면 리팩토링 시에 변경하는 걸로 해보는 건 어떨까요?

2024-10-21 02:31 UTC, rabyeoljji commented on src/views/note/components/pick-drawer.tsx
> +  const [isOpen, setIsOpen] = useState(false)
앗 이것도 코드를 옮기면서 삭제하는 걸 깜박했습니다ㅋㅋ큐ㅠ

2024-10-21 02:36 UTC, rabyeoljji commented on src/views/note/components/quiz-card.tsx
> +        {quizType === 'multiple' && (
오 그러네요! 너무 좋습니다👍

2024-10-21 02:37 UTC, rabyeoljji commented on src/views/quiz-note/components/animate-buttons.tsx
> +  }
아 그러면 되겠군여! 저도 저 부분이 살짝 찝찝했는데ㅋㅋ큐ㅠ

2024-10-21 02:41 UTC, rabyeoljji commented on src/views/quiz-note/components/note-card.tsx
네 삭제해야겠네요!

2024-10-21 02:45 UTC, rabyeoljji commented on src/views/quiz-note/components/set-folder-name-content.tsx
저도 점점 구현을 하다 보니 응집도를 높이는 게 중요하다는 것을 깨닫는 중입니다...ㅎㅎㅠㅠㅠ 적용해서 수정해볼게요!

2024-10-21 02:58 UTC, rabyeoljji commented on src/views/shared/new-quiz-drawer.tsx
> +                onClick={() => setIsOpenMoreStar(true)} // 임시
아아 사실 이게 좀 여러가지 이유인데ㅋㅋㅋ큐ㅠㅠ

1. dialog도 내부에서 trigger를 이용할 수 있다는 사실을 몰랐다 + dialog요소가 drawer요소 내부에 있어도 문제 없이 괜찮은 구조인건지 확신이 없었다. => button과 dialog 분리

2. 같은 버튼인데 별 개수가 부족할 때만 클릭했을 때 dialog가 떠야하는 거면 클릭했을 때 부족한지/아닌지를 boolean으로 판단해서 상태로 저장하고 해당 상태에 따라 dialog가 동작하면 되지 않을까 생각했습니다...

2024-10-21 03:04 UTC, rabyeoljji commented on src/views/shared/move-note-drawer.tsx
>    const [isOpen, setIsOpen] = useState(false)
맞습니다 마찬가지로 분리하고 삭제를 깜박했습니다...ㅋㅋ큐ㅠㅠ

2024-10-21 03:06 UTC, rabyeoljji commented on src/views/shared/more-star-dialog.tsx
> +const MoreStarDialog = ({ isOpen, setIsOpen }: Props) => {
https://github.com/picktoss/pick-toss-next/pull/216#discussion_r1808041351

2024-10-21 03:11 UTC, rabyeoljji commented on src/views/note/index.tsx
저도 네이밍을 note와 note-detail 중에 좀 고민했는데 note-detail로 바꾸는 게 좋을 것 같네요!

2024-10-21 03:12 UTC, rabyeoljji commented on src/views/note/index.tsx
엇 저도 그 부분 정우님께 제안을 드리고 싶었는데ㅎㅎ 좋습니다!

2024-10-21 05:33 UTC, rabyeoljji commented on src/shared/components/ui/button.tsx
> +        special: 'bg-gradient-to-r from-blue-400 from-0% via-[#FFA25F] to-orange-500 to-70%',
아 기존에는 orange => blue라서 
![스크린샷 2024-10-21 142831](https://github.com/user-attachments/assets/54e7684a-48ec-43d7-a534-fe5a8f3c7950)
이 색상이었는데 이번에 만들다보니 디자인이랑 뭔가 다른 것 같아서 ui 살펴보니까 색상이 아래로 바뀌었더라고요
![스크린샷 2024-10-21 141903](https://github.com/user-attachments/assets/c02a9da2-ce17-4139-b8ca-8f74680a769d)
via나 % 넣은 건 바로 blud에서 orange로 가는 거랑 중간에 아래처럼 밝아지는 부분이 있는 거랑 큰 버튼에서 느낌이 많이 다르길래 디자인 시안이랑 최대한 비슷하게 맞추기 위해 넣었습니다.
![스크린샷 2024-10-21 141800](https://github.com/user-attachments/assets/6e66280a-d2eb-4af9-848f-236ba0693964)

2024-10-21 14:07 UTC, jw-r approved these changes
너무 좋습니다!
고생하셨어요🙌

몇가지 코맨트만 확인 부탁드려요👍👍👍

2024-10-21 14:07 UTC, jw-r commented on src/shared/components/ui/input.tsx
> +
right 처럼 아래 div에 포함되고, input에 padding left 주는 방식으로 구현하는 편이 조금 변화에 대응하기 수월할 수 있을 것 같아요!
예를들어, input의 radius 변경이 필요할 때, left 사이드와 right 사이드를 구분할 필요가 없을 것 같습니다👍

2024-10-21 14:07 UTC, jw-r commented on src/views/note/note-search/index.tsx
> +  const searchInputRef = useRef<HTMLDivElement>(null)
searchHeaderRef 가 좀 더 역할에 맞는 네이밍일 수 있을 것 같습니다!

2024-10-22 02:08 UTC, merged