fix: 퀴즈노트 drawer width 조정 및 css 수정
picktoss/pick-toss-next pull request #221
Opened 2024-10-23 09:31 UTC by rabyeoljji

## 개요

### 세부 내용
- drawer max-w-mobile 적용
- 맞춰서 overlay 및 dropdown menu 위치 영역 안쪽으로 조정

### 관련 링크

2024-10-24 15:36 UTC, jw-r requested changes
넘 고생하셨어요!
몇가지 코맨트만 확인 부탁드려요🙌

2024-10-24 15:36 UTC, jw-r commented on src/views/note/create-note/ui/folder-select-drawer.tsx
> +          <div className="flex h-[calc(100%-58px)] flex-col border-b border-border-divider">
-58px은 무엇을 위해서였나용?

2024-10-24 15:36 UTC, jw-r commented on src/views/note/note-detail/components/add-collection-drawer.tsx
> +        overlayProps={{ className: 'max-w-mobile mx-auto' }}
overlay의 width도 max-w-mobile을 적용하기 위함일까요?

2024-10-24 15:36 UTC, jw-r commented on src/views/note/quiz-note/components/dimmed-background.tsx
> +        'fixed top-0 right-1/2 translate-x-1/2 h-screen w-dvw max-w-mobile pointer-events-none opacity-0 transition-all duration-400',
overlay나 dimmed 처리도 mobile width 맞출 필요가 있을까하는 생각이 들었던 것 같아요!
남은 공간을 다양한 요소로 활용할 수 있기 때문에 화면 전체를 dimmed처리해주는 것이 자연스러울 것 같습니다!

2024-10-25 05:10 UTC, rabyeoljji commented on src/views/note/create-note/ui/folder-select-drawer.tsx
> +          <div className="flex h-[calc(100%-58px)] flex-col border-b border-border-divider">
오잉 여기 css 잘못됐네요ㅎㅎㅠㅠㅠ
```
        <div className="flex h-[calc(100%-52px)] w-full flex-col bg-background-base-01">
          <div className="flex max-h-[calc(100%-58px)] flex-col border-b border-border-divider">
```
이렇게 수정할 예정입니다!
-52px은 drawer 내부 상단 header와 sidebar 및 여백의 총 합을 제외한 높이를 계산하기 위함이고
-58px은 하단 폴더 추가 영역과 여백을 제외한 컨텐츠 높이를 계산하기 위함입니다!

컨텐츠 부분을 max-h로 수정했는데 figma로 다시 시안을 확인해본 결과 하단 폴더추가 버튼이 컨텐츠 길이가 짧아도 바로 밑에 있어야해서 저렇게 수정했습니다.

2024-10-25 05:15 UTC, rabyeoljji commented on src/views/note/note-detail/components/add-collection-drawer.tsx
> +        overlayProps={{ className: 'max-w-mobile mx-auto' }}
네 dialog와 다르게 drawer는 좌우가 화면 끝에 붙어있는 형태라 overlay도 같이 조절해주지 않으면 좀 어색하더라고요
웹에서 보이는 느낌이 이런 느낌이라...

<img src="https://github.com/user-attachments/assets/a564ef4a-a8dc-49f2-93fd-ba942aec23e6" width="50%" /><img src="https://github.com/user-attachments/assets/9d8700c8-3020-48df-acf2-c5cfe95d25ed" width="50%" />

2024-10-25 05:17 UTC, rabyeoljji commented on src/views/note/quiz-note/components/dimmed-background.tsx
> +        'fixed top-0 right-1/2 translate-x-1/2 h-screen w-dvw max-w-mobile pointer-events-none opacity-0 transition-all duration-400',
https://github.com/picktoss/pick-toss-next/pull/221#discussion_r1816007655
음... 다른 코멘트에 둔 답변과 마찬가지로 drawer는 overlay가 화면 전체를 덮으면 좀 부자연스럽다고 느껴져요! 화면의 모든 모서리와 떨어져있는 dialog같은 경우에는 괜찮은데 drawer는 경계가 닿아있는 느낌을 주는 요소라...

2024-10-27 15:58 UTC, jw-r commented on src/views/note/note-detail/components/add-collection-drawer.tsx
> +        overlayProps={{ className: 'max-w-mobile mx-auto' }}
띠용... 둘다 조금 이상한 것 같아요 ㅋㅋㅋ
모바일 온리가 이런 문제가 있군요 🤣

2024-10-27 15:59 UTC, jw-r approved these changes
넘 좋습니다!
고생하셨어요👍

2024-10-28 06:21 UTC, rabyeoljji commented on src/views/note/note-detail/components/add-collection-drawer.tsx
> +        overlayProps={{ className: 'max-w-mobile mx-auto' }}
그쵸ㅠㅠㅎㅎ 저도 이 부분이 좀 아쉽긴 하더라고요😂 제 눈엔 오른쪽이 나은 것 같아서 일단 overlay도 같이 맞췄습니다...ㅎㅎ 이 부분은 팀 회의에서 논의해봐도 좋을 것 같아요!

2024-10-28 07:40 UTC, merged