feat: profile - today quiz
picktoss/pick-toss-next pull request #222
Opened 2024-10-24 08:53 UTC by rabyeoljji

## 개요
<img src="https://github.com/user-attachments/assets/0ac6c01e-c495-4858-822d-1651d1e2bdff" width="30%" />

### 세부 내용
- 오늘의 퀴즈 현황 페이지 퍼블리싱 / 스토리북

### 관련 링크

2024-10-27 15:56 UTC, jw-r requested changes
너무 좋습니다!

몇가지 코맨트만 확인 부탁드려요~!

2024-10-27 15:56 UTC, jw-r commented on src/views/profile/today-quiz/components/day-item/index.stories.tsx
누가 이렇게 훌륭한 스토리를 작성한거죠..?
이제 스토리북을 활용한 테스트만 해보면 스토리북 정복입니다🤩

2024-10-27 15:56 UTC, jw-r commented on src/views/profile/today-quiz/components/day-item/index.tsx
> +          <Text typography="text2-bold" className={isLast ? 'text-[#FB7E20]' : 'text-[#797D81]'}>
컨벤션처럼 cn함수를 사용하면 좋을 것 같아요!

2024-10-27 15:56 UTC, jw-r commented on src/views/profile/today-quiz/components/day-check/index.tsx
> +  ]
이 데이터가 여기에있으니 뭔가 불편하지 않으신가요?
스토리를 작성할 때, DayCheck를 온전히 활용하지 못하고 또다른 Wrapper Jsx가 필요하게되죠.
DayCheck 컴포넌트가 checkData를 props로 받는다면, 즉 순수함수라면 스토리를 작성할 때에도 DayCheck 컴포넌트를 그대로 활용할 수 있었을 것 같아요!

하지만 그렇다고 checkData를 상위에서 fetch하자니 상위 컴포넌트가 client 컴포넌트가 되거나, 데이터에 변경이 있을 때마다 router.refresh 등을 해줘야하는 문제가 발생할 수 있습니다 하핫..

이번엔 checkData를 props으로 넘겨서 DayCheck 함수를 그대로 활용해보고, 다음에 또 같이 고민해보죠!

2024-10-27 15:56 UTC, jw-r commented on src/views/profile/today-quiz/index.tsx
> +        </button>
page 단은 왠만해선 client 컴포넌트가 되지 않는 것이 좋습니다!
해당 button을 분리해봐도 좋을 것 같아요👍

2024-10-28 06:30 UTC, rabyeoljji commented on src/views/profile/today-quiz/components/day-check/index.tsx
> +  ]
아 맞아요 DayCheck 구현할 때 저도 그 부분이 좀 고민되더라고요! 네 그러면 일단 props로 넘기고 받는 쪽으로 수정하고 저도 좀 더 고민해볼게요ㅎㅎ

2024-10-28 06:48 UTC, rabyeoljji commented on src/views/profile/today-quiz/index.tsx
> +        </button>
너무 좋은 생각인 것 같습니다! 계속 반복해서 사용되다 보니까 아예 공통 컴포넌트로 분리하는 방법도 생각해봤어요!

2024-10-28 08:23 UTC, jw-r approved these changes
너무너무 좋습니다!
고생하셨어요🙌

2024-10-29 03:31 UTC, merged