feat: profile - email verification
picktoss/pick-toss-next pull request #230
Opened 2024-10-31 09:21 UTC by rabyeoljji

## 개요
![스크린샷 2024-10-31 174610](https://github.com/user-attachments/assets/c6fde8a5-6a61-40a9-a707-5067752b3278)

### 세부 내용
- 이메일 인증 화면 퍼블리싱 + 스토리북 작성

### 관련 링크

2024-11-01 15:30 UTC, jw-r requested changes
근아님 너무 고생하셨습니다🙌

몇 가지 코맨트 확인 부탁드릴게요!

2024-11-01 15:30 UTC, jw-r commented on src/features/email/components/email-verification/index.stories.tsx
> +const EmailVerificationWithArgs = ({
이럴 땐 isAollowed와 activeSaveButton이 prop으로 전달될 수 없는지 고민해봐도 좋을 것 같아요!
컨텍스트를 사용한다고해서 모든 상태를 컨텍스트로 관리할 필요는 없으니까요👍

2024-11-01 15:30 UTC, jw-r commented on src/features/email/components/email-verification/index.stories.tsx
> +export const Default: Story = {
이메일 주소를 입력하고 확인을 누르면 다음 프로세스로 넘어가도록 컴포넌트 테스트를 진행해보면 어떨까요?
https://storybook.js.org/docs/writing-stories/play-function

2024-11-01 15:30 UTC, jw-r commented on src/app/(routes)/(tabs)/profile/verify-email/page.tsx
> +      <main className="flex h-[calc(100dvh-54px-88px)] w-full flex-col overflow-y-auto px-[16px]">
이 부분은 사실상 레이아웃이고, VerifyStateHeader와 EmailVerification이 한번 더 추상화된다면 컨텍스트를 사용하지 않아도 되고 컴포넌트 테스트도 간단해질 것 같아요!
컨텍스트를 사용하면 구현이 편하지만, 테스트가 어려운 등의 문제가 있으니 꼭 필요한 경우에만 사용해도 좋을 것 같아요👍

2024-11-03 07:15 UTC, rabyeoljji commented on src/app/(routes)/(tabs)/profile/verify-email/page.tsx
> +      <main className="flex h-[calc(100dvh-54px-88px)] w-full flex-col overflow-y-auto px-[16px]">
아 그런 문제가 있군요...! 그러면 전반적으로 상태관리 코드를 수정을 좀 해봐야겠네요;;

2024-11-03 07:15 UTC, rabyeoljji commented on src/features/email/components/email-verification/index.stories.tsx
> +export const Default: Story = {
오오 한 번 시도해볼게요!

2024-11-03 15:40 UTC, jw-r approved these changes
너무 좋습니다!
고생하셨어요👍

스토리북을 통한 컴포넌트 테스트 어떠셨나요 ㅋㅋ 저는 귀찮아서 잘 안하게 되는데...이런 것도 있다 정도의 인사이트를 드리고 싶었습니다!

몇가지 코맨트 확인 부탁드려요!
수정할 점이 있으시다면 수정하시고 바로 merge해도 될 것 같습니다!

2024-11-03 15:40 UTC, jw-r commented on src/features/email/components/email-verification/index.stories.tsx
> +    await userEvent.click(confirmButton)
너무너무 좋아요👍

2024-11-03 15:40 UTC, jw-r commented on src/app/(routes)/(tabs)/profile/verify-email/page.tsx
> +      <EmailVerification isAllowed={isAllowed} setIsAllowed={setIsAllowed} />
상태가 반드시 필요한 상황이군요
다만 페이지 컴포넌트를 client 컴포넌트로 활용하는 것은 app router에서는 안티패턴에 해당합니다 (저도 ui그릴 땐 대충 해놓긴 하는데...ㅠ)
두 컴포넌트가 한번 더 추상화 되어도 괜찮았을 것 같습니다!

2024-11-03 15:40 UTC, jw-r commented on src/features/email/components/verify-email-input/index.tsx
> +  // }, [])
verifyEmailInput의 prop으로 기존 사용자의 이메일을 받을 수도 있겠네요
혹은 verifyEmailInput 내부에서 사용자 정보를 불러온 후, email의 초기 값으로 들어갈 수도 있을 것 같아요!
useEffect 없이도 구현이 가능할지도 모르겠습니다!

2024-11-03 15:40 UTC, jw-r commented on src/features/email/components/verify-email-input/index.tsx
> +  }, [email])
이메일이 변경될때마다 handleEmailChange와 함께 두번 이 로직이 실행되네요
사용자가 기존에 이메일을 가지고 있을 경우, 해당 이메일에 대한 유효성 검사를 수행하고 싶으셨던 걸까요?
이미 db에 저장될 때, 유효성 검사를 마친 이메일만 저장하기 때문에 불필요한 검사일 수 있습니다🙌

2024-11-03 15:40 UTC, jw-r commented on src/features/email/components/verify-email-input/index.tsx
> +    }
너무 좋은데요...?

2024-11-04 02:53 UTC, rabyeoljji commented
> 너무 좋습니다! 고생하셨어요👍
> 
> 스토리북을 통한 컴포넌트 테스트 어떠셨나요 ㅋㅋ 저는 귀찮아서 잘 안하게 되는데...이런 것도 있다 정도의 인사이트를 드리고 싶었습니다!
> 
> 몇가지 코맨트 확인 부탁드려요! 수정할 점이 있으시다면 수정하시고 바로 merge해도 될 것 같습니다!

너무 새롭더라고요..! 스토리북을 제대로 만든다하면 확실히 있으면 좋을 것 같은 기능이었어요ㅋㅋㅋ 뭔가 좀 더 제대로 구현하려면 좀 더 공부가 필요할 것 같긴 하지만요ㅎㅎ 귀찮음은 인정입니다...ㅋㅋㅋㅋ 정우님 덕분에 이런 기능이 있다는 것도 알게 되고 사용도 해봐서 너무 좋은 경험이었어요ㅎㅎ

2024-11-04 03:02 UTC, rabyeoljji commented on src/features/email/components/verify-email-input/index.tsx
> +  }, [email])
아 저 부분이 input 입력 값이 이메일 형식일 때만 확인 버튼을 활성화하는 로직을 구현하기 위해서 현재 확인 버튼을 활성화하는 로직이 isValid가 true이면 활성화하는 식으로 진행하고 있는데, 이게 도메인 추천 영역에서 클릭해서 자동완성을 한 경우에는 onChange로 감지가 안돼서 isValid 활성화가 안돼서 확인 버튼이 활성화가 안되는 문제가 있더라고요ㅠㅠ 정우님이 말씀하신 케이스는 테스트를 못해봤는데 아마 기존 이메일이 들어올 경우에도 그렇게 동작할 것 같아요...! 그래서 저렇게 useEffect로 확인버튼을 활성화하는 방법을 적용했는데 혹시 다른 좋은 방법이 있을까요?

2024-11-04 03:03 UTC, rabyeoljji commented on src/app/(routes)/(tabs)/profile/verify-email/page.tsx
> +      <EmailVerification isAllowed={isAllowed} setIsAllowed={setIsAllowed} />
어쩔 수 없군요...ㅋㅋ큐ㅠㅠ

2024-11-04 03:07 UTC, jw-r commented on src/features/email/components/verify-email-input/index.tsx
> +  }, [email])
그런 의도가 있었군요!
이해했습니다. 잘 작성된 코드네요👍

다만 가독성과 편의성을 위해 zod, react-hook-form의 도입을 고려해봐도 좋을 것 같습니다!

2024-11-04 03:31 UTC, rabyeoljji commented on src/features/email/components/verify-email-input/index.tsx
> +  }, [email])
> 그런 의도가 있었군요! 이해했습니다. 잘 작성된 코드네요👍
> 
> 다만 가독성과 편의성을 위해 zod, react-hook-form의 도입을 고려해봐도 좋을 것 같습니다!

오오... 너무 좋은데요? 추후에 한 번 적용해볼까봐요...!

2024-11-04 04:05 UTC, merged