refactor: floating button bottom값 조정
picktoss/pick-toss-next pull request #237
Opened 2024-11-05 07:36 UTC by rabyeoljji

## 개요

### 세부 내용
- bottom nav가 빠지면서 floating 버튼 위치가 디자인보다 높았던 부분 수정

+ fix
tab을 searchParams로 관리하다보니 생기는 문제 해결
: tab을 바꾼 후 뒤로가기 버튼을 눌렀을 때 기대되는 것은 해당 화면에서 나가는 것
=> 실제로는 tab이 이전 tab으로 바뀌는 식으로 동작

x (cancel) 버튼일 경우 고정된 이전 페이지가 있는 것이 아니라 이전 페이지를 저장해뒀다가 이동하는 방식으로 구현
<- (goback) 버튼일 경우 고정된 페이지로 replace하는 방식으로 구현

### 관련 링크

2024-11-05 10:10 UTC, jw-r requested changes
고생하셨습니다!

몇 가지 코맨트 확인 부탁드려요🙏

2024-11-05 10:10 UTC, jw-r commented on src/features/note/components/swipeable-note-card.tsx
> +        !isSelectMode && !isDragging && !isSwiped && router.push(`/note/${id}?previousPath=/note`)
사용자에게 노출시킬 필요가 없는 searchParam이라는 생각도 조금 들었던 것 같아요!

2024-11-05 10:10 UTC, jw-r commented on src/app/(routes)/note/[id]/(main)/@header/default.tsx
> +  }, [])
관련 로직을 usePreviousPath로 추상화 해보는 것은 어떨까요?
usePreviousPath() 훅을 호출하면 현재 path를 session에 저장하고,
{getPreviousPath} = usePreviousPath() 와 같이 이전 path를 가져오는 기능도 함께 들어있으면 좋을 것 같아요!

PreviousPathProvider를 최산단 layout에 적용하고, 그 안에서 usePreviousPath() 호출.
session저장 로직 useEffect의 의존성으로 pathname을 추가하면 searchParams를 신경쓰지 않고도 항상 사용자의 이전 페이지를 알 수 있을 것 같아요!

2024-11-05 11:02 UTC, rabyeoljji commented on src/app/(routes)/note/[id]/(main)/@header/default.tsx
> +  }, [])
정말 천재적인 생각입니다...👍최고에요

2024-11-06 11:21 UTC, jw-r approved these changes
LGTM!!

2024-11-06 13:23 UTC, merged