feat: star charge
picktoss/pick-toss-next pull request #243
Opened 2024-11-07 15:37 UTC by rabyeoljji

## 개요
팀 회의 때 논의된 것 처럼 별 충전 페이지가 우선적으로 진행되어야 될 것 같아 먼저 퍼블리싱 진행했습니다!

### 세부 내용

### 관련 링크

2024-11-08 10:49 UTC, jw-r requested changes
너무너무 고생하셨습니다!🥹

몇가지 코맨트만 확인 부탁드려요!

2024-11-08 10:49 UTC, jw-r commented on src/app/(routes)/star-charge/page.tsx
> +      <StarChargeHeader />
여기 header는 components 폴더에 따로 구현하신 이유가 있을까용?

2024-11-08 10:49 UTC, jw-r commented on src/app/(routes)/star-charge/page.tsx
> +              src={SHINY_STAR_IMG}
이렇게 사용하신 이유가 있을까요?
width, height를 지정하기 어려우셨다면 아래와 같이 사용해보면 어떨까요?
```tsx
<div className="relative">
  <Image src="/images/star-shiny.png" fill />
</div>
```

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/constants/product-info-list.tsx
원시타입이 아니라면 config 폴더에 넣는 건 어떨까요?
이것도 컨벤션이 있으면 좋을 것 같아서요!

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/star-instruction-drawer/index.tsx
> +        <header className="mt-[16px] flex w-full items-center justify-between px-[18px] mt-[24px]">
margin top이 두번 지정되어있네용!

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/star-instruction-drawer/index.tsx
> +        <header className="mt-[16px] flex w-full items-center justify-between px-[18px] mt-[24px]">
DrawerHeader를 사용하지 않으신 이유가 있을까요?

2024-11-08 10:49 UTC, jw-r commented on src/features/star/components/invite-reward/index.tsx
> +          <header className="mt-[40px] flex flex-col w-full items-center gap-[24px]">
여기도 DrawerHeader 컴포넌트를 활용해봐도 좋을 것 같아용!

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/star-charge-header/index.tsx
> +      </button>
```suggestion
      <GoBackButton icon="cancel" />
```

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/product-container/index.tsx
> +      className="flex h-fit min-h-[200px] w-dvw max-w-mobile snap-x gap-[8px] overflow-x-scroll px-[16px] scrollbar-hide"
이런 컴포넌트들에는 select-none 스타일이 들어가면 좋을 것 같아용!

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/product-container/index.tsx
> +    }
배경이 scrollable해서 의도대로 동작하지 않는 것 같습니다!
좌우로 휠 했을 때는 버벅임이 발생하고 있습니다
터치 and drag로도 좌우 이동이 가능하면 좋을 것 같아요!

2024-11-08 10:49 UTC, jw-r commented on src/features/payment/components/star-charge/product-container/index.tsx
> +        <motion.div key={product.key} className="snap-center" style={{ scrollSnapAlign: 'center' }}>
```suggestion
        <motion.div key={product.key} className="snap-center">
```

2024-11-09 06:56 UTC, rabyeoljji commented on src/app/(routes)/star-charge/page.tsx
> +      <StarChargeHeader />
아아 제가 이것 때문에 꽤 시간이 걸렸는데 어떻게든지 Layout에서 header로 받아서 해보려고 했지만 background image랑 뭔가 충돌이 있는지 화면에서 보이지 않더라고요ㅠㅠ

2024-11-09 07:05 UTC, rabyeoljji commented on src/app/(routes)/star-charge/page.tsx
> +              src={SHINY_STAR_IMG}
흠 이 페이지를 만들면서 고민이 좀 됐던 부분이 배경 이미지가 있고 폰트 색상이 그에 맞춰져 있어서 요소들의 크기와 위치를 고정하면 디바이스의 크기에 따라 의도와 너무 다른 화면이 되더라고요... 그래서 최대한 화면 크기에 따라 유연하게 조절이 되는 걸 의도하긴 했어요! 비슷한 이유로 메인 영역이 스크롤되는 경우도 최대한 피하는 쪽으로 작성했습니다ㅠㅠ

2024-11-09 07:07 UTC, rabyeoljji commented on src/features/payment/constants/product-info-list.tsx
오오 좋습니다! 그러면 constants에는 원시타입만 두고 아니면 config에 넣는 쪽으로 맞출까요?

2024-11-09 07:08 UTC, rabyeoljji commented on src/features/payment/components/star-charge/star-instruction-drawer/index.tsx
> +        <header className="mt-[16px] flex w-full items-center justify-between px-[18px] mt-[24px]">
앗 DrawerHeader 깜박했습니다ㅋㅋㅋ

2024-11-09 07:18 UTC, rabyeoljji commented on src/features/payment/components/star-charge/product-container/index.tsx
> +    }
맞아요...! 그 부분 보완해서 업데이트할 예정이었습니다ㅎㅎ

2024-11-09 08:57 UTC, rabyeoljji commented on src/app/(routes)/star-charge/page.tsx
> +      <StarChargeHeader />
아닛... 다시 develop pull받고 install 하니까 Layout에서 header 받아서 렌더링 됩니다... 뭔가 병렬 라우트가 작동이 안 됐었나봐요ㅠㅠ 이 방법으로 수정할 예정입니다ㅋㅋ큐ㅠㅠ

2024-11-09 12:39 UTC, jw-r commented on src/app/(routes)/star-charge/page.tsx
> +              src={SHINY_STAR_IMG}
요거랑 이미지를 import해서 사용하는 것과 어떤 연관이 있을까요?
이미지 경로를 넣어줘도 동일하게 구현이 가능한 부분인 것 같아서요!

2024-11-09 12:39 UTC, jw-r commented on src/features/payment/constants/product-info-list.tsx
넘 좋아용!

2024-11-09 13:38 UTC, rabyeoljji commented on src/app/(routes)/star-charge/page.tsx
> +              src={SHINY_STAR_IMG}
> 요거랑 이미지를 import해서 사용하는 것과 어떤 연관이 있을까요? 이미지 경로를 넣어줘도 동일하게 구현이 가능한 부분인 것 같아서요!

앗 정우님 말씀을 잘못 이해했었네요ㅋㅋ큐ㅠㅠ 이렇게 하는 방법이 있었군요...! 이 방법 적용한 김에 살짝 보완했습니다!

2024-11-12 12:55 UTC, closed without merging