feat: 퀴즈 노트 메인 페이지에서 디렉토리에 해당하는 모든 문서 가져오는 부분
picktoss/pick-toss-next pull request #259
Opened 2024-11-18 13:54 UTC by rabyeoljji

## 개요

### 세부 내용

### 관련 링크

2024-11-18 15:31 UTC, jw-r requested changes
넘 좋습니다!
몇가지 코맨트만 확인부탁드려용🙌

2024-11-18 15:31 UTC, jw-r commented on src/types/document.d.ts
> +export declare namespace Document {
export 하실필요없습니다
위에서 생성한 Document 인터페이스와 네이밍이 겹쳐서 발생하는 문제입니다!
인터페이스 부분을 DocumentItem으로 변경해주세요

네임 스페이스가 이런 단점이 있네요

2024-11-18 15:31 UTC, jw-r commented on src/features/pages/documents-in-directory.tsx
> +  }, [data])
요건 데이터 확인을 위해서 임시로 둔걸까요?

2024-11-19 02:06 UTC, rabyeoljji commented on src/types/document.d.ts
> +export declare namespace Document {
아하 그것 때문에 생긴 문제였군여...!

2024-11-19 02:07 UTC, rabyeoljji commented on src/features/pages/documents-in-directory.tsx
> +  }, [data])
네 맞습니다! 확인용이라 나중에 삭제될 코드입니다

2024-11-19 04:09 UTC, jw-r approved these changes
LGTM!!
고생하셨습니다🙌

2024-11-19 06:57 UTC, merged